//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDPortal.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPDPortalEntities : DbContext
    {
        public CPDPortalEntities()
            : base("name=CPDPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Sponsor> Sponsors { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<TherapeuticArea> TherapeuticAreas { get; set; }
        public virtual DbSet<TherapeuticProgram> TherapeuticPrograms { get; set; }
        public virtual DbSet<RequestStatusLookup> RequestStatusLookups { get; set; }
        public virtual DbSet<UserTypeLookUp> UserTypeLookUps { get; set; }
        public virtual DbSet<ProgramRequestSessionCredit> ProgramRequestSessionCredits { get; set; }
        public virtual DbSet<TerritoryLookUp> TerritoryLookUps { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<SpeakerPayment> SpeakerPayments { get; set; }
        public virtual DbSet<UserProvince> UserProvinces { get; set; }
        public virtual DbSet<UserTerritory> UserTerritories { get; set; }
        public virtual DbSet<ProgramRequestFileUploadOther> ProgramRequestFileUploadOthers { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<PayeeInfo> PayeeInfoes { get; set; }
        public virtual DbSet<ProgramRequest> ProgramRequests { get; set; }
        public virtual DbSet<ProgramRequestFileUpload> ProgramRequestFileUploads { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<COISlidesUpload> COISlidesUploads { get; set; }
        public virtual DbSet<TerritoryIDRegionLookup> TerritoryIDRegionLookups { get; set; }
        public virtual DbSet<UserInfo_Production_SalesRepSpeakers> UserInfo_Production_SalesRepSpeakers { get; set; }
        public virtual DbSet<UserInfo_Production_SpeakerOnly> UserInfo_Production_SpeakerOnly { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<SessionCreditLookUp> SessionCreditLookUps { get; set; }
        public virtual DbSet<AssignedRole> AssignedRoles { get; set; }
        public virtual DbSet<ProgramModulesLookup> ProgramModulesLookups { get; set; }
        public virtual DbSet<ProgramRequestModule> ProgramRequestModules { get; set; }
    }
}
