//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramRequestModule
    {
        public int ID { get; set; }
        public Nullable<int> ProgramRequestID { get; set; }
        public Nullable<bool> ProgramModule1 { get; set; }
        public Nullable<bool> ProgramModule2 { get; set; }
        public Nullable<bool> ProgramModule3 { get; set; }
        public Nullable<bool> ProgramModule4 { get; set; }
        public Nullable<bool> ProgramModule5 { get; set; }
        public Nullable<bool> ProgramModule6 { get; set; }
        public Nullable<bool> ProgramModule7 { get; set; }
        public Nullable<bool> ProgramModule8 { get; set; }
        public Nullable<bool> ProgramModule9 { get; set; }
        public Nullable<bool> ProgramModule10 { get; set; }
    }
}
