//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionCreditLookUp
    {
        public int SessionCreditID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Comment { get; set; }
        public string Descriptionfr { get; set; }
    }
}
