//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapeuticProgram
    {
        public int ID { get; set; }
        public Nullable<int> TherapeuticID { get; set; }
        public Nullable<int> ProgramID { get; set; }
    
        public virtual TherapeuticArea TherapeuticArea { get; set; }
        public virtual Program Program { get; set; }
    }
}
