//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapeuticArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TherapeuticArea()
        {
            this.Privileges = new HashSet<Privilege>();
            this.TherapeuticPrograms = new HashSet<TherapeuticProgram>();
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int TherapeuticID { get; set; }
        public string TherapeuticName { get; set; }
        public string TherapeuticTitle { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ActivePrograms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Privilege> Privileges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapeuticProgram> TherapeuticPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
